name: oaplayer
description: OAPlayer By Luckykeeper
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_meedu_videoplayer: ^4.2.12+1
  wakelock: ^0.6.2

flutter:
  uses-material-design: true
